# Generated by Django 3.2.8 on 2021-10-26 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=50, verbose_name='Карьера')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Карьера',
                'verbose_name_plural': 'Карьеры',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('world_premiere', models.DateField(null=True, verbose_name='Премьера в мире')),
                ('russian_premiere', models.DateField(null=True, verbose_name='Премьера в России')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
                ('poster', models.ImageField(upload_to='poster/%Y/%m/%d', verbose_name='Постер')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('rating', models.FloatField(verbose_name='Рейтинг фильма')),
                ('views', models.IntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('man', 'мужчина'), ('woman', 'женщина'), ('other', 'другое')], max_length=5)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('avatar', models.ImageField(upload_to='avatar/%Y/%m/%d', verbose_name='Аватар')),
                ('point', models.IntegerField(default=0, verbose_name='Очки пользователя')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='film.countrymodel', verbose_name='Страна')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TrailerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name='Ссылка на трейлер')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='film.filmmodel', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Трейлер',
                'verbose_name_plural': 'Трейлеры',
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='person/%Y/%m/%d', verbose_name='Фото')),
                ('biography', models.TextField(max_length=500, verbose_name='Биография')),
                ('birthday', models.DateField(verbose_name='День рождение')),
                ('death_day', models.DateField(blank=True, null=True, verbose_name='День смерти')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('career', models.ManyToManyField(to='film.CareerModel', verbose_name='Карьера')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='film.countrymodel', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='ImageFilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='film/%Y/%m/%d')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.filmmodel', verbose_name='Фильм')),
            ],
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='actor',
            field=models.ManyToManyField(related_name='actor_film', to='film.PersonModel', verbose_name='Актер'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='composer',
            field=models.ManyToManyField(related_name='composer_film', to='film.PersonModel', verbose_name='Композитор'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='film.countrymodel', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='director',
            field=models.ManyToManyField(related_name='director_film', to='film.PersonModel', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='genre',
            field=models.ManyToManyField(to='film.GenreModel', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='producer',
            field=models.ManyToManyField(related_name='producer_film', to='film.PersonModel', verbose_name='Продюсер'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='scenario',
            field=models.ManyToManyField(related_name='scenario_film', to='film.PersonModel', verbose_name='Сценарист'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('rating', models.FloatField(verbose_name='Рейтинг комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.filmmodel', verbose_name='Комментируемый фильм')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
