# Generated by Django 3.2.8 on 2021-10-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20211026_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careermodel',
            options={'ordering': ['career'], 'verbose_name': 'Карьера', 'verbose_name_plural': 'Карьеры'},
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['date_create'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='countrymodel',
            options={'ordering': ['country'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='filmmodel',
            options={'ordering': ['name', 'date_create'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genremodel',
            options={'ordering': ['genre'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='imagefilmmodel',
            options={'ordering': ['date_create'], 'verbose_name': 'Кадр', 'verbose_name_plural': 'Кадры'},
        ),
        migrations.AlterModelOptions(
            name='personmodel',
            options={'ordering': ['name', 'date_create'], 'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
        migrations.AlterModelOptions(
            name='trailermodel',
            options={'ordering': ['film'], 'verbose_name': 'Трейлер', 'verbose_name_plural': 'Трейлеры'},
        ),
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'ordering': ['date_create'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг фильма'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='biography',
            field=models.TextField(max_length=2000, verbose_name='Биография'),
        ),
    ]
